version: "3"

services:
  metrics:
    image: prom/prometheus
  discovery:
    image: consul
    command: agent -server -bootstrap -client 0.0.0.0 -ui
  server:
    image: goal
    build: .
    ports:
      - 8080:8080
    environment:
      GOAL_DISCOVERY_ENABLE: "true"
      GOAL_DISCOVERY_ADDRESS: "discovery"
      GOAL_DISCOVERY_SCHEME: "http"
      GOAL_CLUSTER_ENABLE: "true"