// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/proto/goal.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoalMessageEnvelope struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Messages             []*any.Any `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GoalMessageEnvelope) Reset()         { *m = GoalMessageEnvelope{} }
func (m *GoalMessageEnvelope) String() string { return proto.CompactTextString(m) }
func (*GoalMessageEnvelope) ProtoMessage()    {}
func (*GoalMessageEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_5923fbff71b92efe, []int{0}
}

func (m *GoalMessageEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoalMessageEnvelope.Unmarshal(m, b)
}
func (m *GoalMessageEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoalMessageEnvelope.Marshal(b, m, deterministic)
}
func (m *GoalMessageEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoalMessageEnvelope.Merge(m, src)
}
func (m *GoalMessageEnvelope) XXX_Size() int {
	return xxx_messageInfo_GoalMessageEnvelope.Size(m)
}
func (m *GoalMessageEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GoalMessageEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GoalMessageEnvelope proto.InternalMessageInfo

func (m *GoalMessageEnvelope) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GoalMessageEnvelope) GetMessages() []*any.Any {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GoalError struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string     `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Details              []*any.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GoalError) Reset()         { *m = GoalError{} }
func (m *GoalError) String() string { return proto.CompactTextString(m) }
func (*GoalError) ProtoMessage()    {}
func (*GoalError) Descriptor() ([]byte, []int) {
	return fileDescriptor_5923fbff71b92efe, []int{1}
}

func (m *GoalError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoalError.Unmarshal(m, b)
}
func (m *GoalError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoalError.Marshal(b, m, deterministic)
}
func (m *GoalError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoalError.Merge(m, src)
}
func (m *GoalError) XXX_Size() int {
	return xxx_messageInfo_GoalError.Size(m)
}
func (m *GoalError) XXX_DiscardUnknown() {
	xxx_messageInfo_GoalError.DiscardUnknown(m)
}

var xxx_messageInfo_GoalError proto.InternalMessageInfo

func (m *GoalError) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GoalError) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GoalError) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type GoalPingRequest struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoalPingRequest) Reset()         { *m = GoalPingRequest{} }
func (m *GoalPingRequest) String() string { return proto.CompactTextString(m) }
func (*GoalPingRequest) ProtoMessage()    {}
func (*GoalPingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5923fbff71b92efe, []int{2}
}

func (m *GoalPingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoalPingRequest.Unmarshal(m, b)
}
func (m *GoalPingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoalPingRequest.Marshal(b, m, deterministic)
}
func (m *GoalPingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoalPingRequest.Merge(m, src)
}
func (m *GoalPingRequest) XXX_Size() int {
	return xxx_messageInfo_GoalPingRequest.Size(m)
}
func (m *GoalPingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoalPingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoalPingRequest proto.InternalMessageInfo

func (m *GoalPingRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GoalPingResponse struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoalPingResponse) Reset()         { *m = GoalPingResponse{} }
func (m *GoalPingResponse) String() string { return proto.CompactTextString(m) }
func (*GoalPingResponse) ProtoMessage()    {}
func (*GoalPingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5923fbff71b92efe, []int{3}
}

func (m *GoalPingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoalPingResponse.Unmarshal(m, b)
}
func (m *GoalPingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoalPingResponse.Marshal(b, m, deterministic)
}
func (m *GoalPingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoalPingResponse.Merge(m, src)
}
func (m *GoalPingResponse) XXX_Size() int {
	return xxx_messageInfo_GoalPingResponse.Size(m)
}
func (m *GoalPingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoalPingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoalPingResponse proto.InternalMessageInfo

func (m *GoalPingResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*GoalMessageEnvelope)(nil), "proto.GoalMessageEnvelope")
	proto.RegisterType((*GoalError)(nil), "proto.GoalError")
	proto.RegisterType((*GoalPingRequest)(nil), "proto.GoalPingRequest")
	proto.RegisterType((*GoalPingResponse)(nil), "proto.GoalPingResponse")
}

func init() { proto.RegisterFile("src/proto/goal.proto", fileDescriptor_5923fbff71b92efe) }

var fileDescriptor_5923fbff71b92efe = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8e, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x59, 0xbb, 0xa9, 0x7d, 0x82, 0x4a, 0x1c, 0x5a, 0x87, 0x87, 0xd2, 0x53, 0x4f, 0xe9,
	0x98, 0x07, 0x8f, 0xe2, 0x61, 0x78, 0x12, 0xa4, 0x17, 0x8f, 0x92, 0xad, 0xcf, 0x10, 0x48, 0xf3,
	0x6a, 0x92, 0x09, 0xfb, 0xef, 0xa5, 0x89, 0x73, 0xe0, 0x60, 0xa7, 0xf7, 0xf8, 0xf2, 0x7b, 0xbf,
	0x2f, 0x30, 0x75, 0x76, 0x5d, 0xf7, 0x96, 0x3c, 0xd5, 0x92, 0x84, 0xe6, 0x61, 0x65, 0x93, 0x30,
	0x66, 0x77, 0x92, 0x48, 0x6a, 0x8c, 0xef, 0xab, 0xcd, 0x67, 0x2d, 0xcc, 0x36, 0x12, 0xe5, 0x3b,
	0x5c, 0xbf, 0x90, 0xd0, 0xaf, 0xe8, 0x9c, 0x90, 0xb8, 0x34, 0xdf, 0xa8, 0xa9, 0x47, 0x76, 0x01,
	0x89, 0x6a, 0xf3, 0x51, 0x31, 0xaa, 0x26, 0x4d, 0xa2, 0x5a, 0x36, 0x87, 0xb3, 0x2e, 0x22, 0x2e,
	0x4f, 0x8a, 0xb4, 0x3a, 0x5f, 0x4c, 0x79, 0x94, 0xf2, 0x9d, 0x94, 0x3f, 0x9b, 0x6d, 0xf3, 0x47,
	0x95, 0x1f, 0x90, 0x0d, 0xe2, 0xa5, 0xb5, 0x64, 0x0f, 0x74, 0x0c, 0xc6, 0x6b, 0x6a, 0x31, 0x4f,
	0x8a, 0x51, 0x95, 0x35, 0x61, 0x67, 0x1c, 0x4e, 0x5b, 0xf4, 0x42, 0x69, 0x97, 0xa7, 0x47, 0x1a,
	0x76, 0x50, 0x59, 0xc3, 0xe5, 0x50, 0xf0, 0xa6, 0x8c, 0x6c, 0xf0, 0x6b, 0x83, 0xce, 0xb3, 0x7b,
	0xc8, 0xbc, 0xea, 0xd0, 0x79, 0xd1, 0xf5, 0xa1, 0x2d, 0x6d, 0xf6, 0x41, 0x39, 0x87, 0xab, 0xfd,
	0x81, 0xeb, 0xc9, 0x38, 0x3c, 0x7e, 0xb1, 0x78, 0x82, 0xf1, 0x40, 0xb3, 0xc7, 0xdf, 0x79, 0x13,
	0xbf, 0xc2, 0xff, 0xf5, 0xce, 0x6e, 0x0f, 0xf2, 0xa8, 0x5f, 0x9d, 0x84, 0xfc, 0xe1, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x79, 0xe0, 0x04, 0x25, 0x9e, 0x01, 0x00, 0x00,
}
