baseURL = "https://wizcorp.github.io/goal"
theme = "docdock"
DefaultContentLanguage = "en"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[languages]
  [languages.en]
    title = "Goal User Guide"
    languageCode = "en-us"
    weight = 1
    [languages.en.params]
        help = "Help"
  [languages.ja]
    title = "Goalユーザーガイド"
    languageCode = "ja-jp"
    weight = 2

    [languages.ja.params]
      [languages.ja.params.navigation]
        help = "ヘルプ"